<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UlpSeeder extends Seeder
{
    public function run(): void
    {
        $ulpData = [
            1 => [ // Kalimantan Barat
                'singkawang',
                'sambas',
                'bengkayang',
                'sei_duri',
                'sekura',
                'pemangkat',
                'sanggau',
                'sintang',
                'putussibau',
                'balai_karangan',
                'sekadau',
                'nanga_pinoh',
            ],
            2 => [ // Kalimantan Selatan
                'lambung_mangkurat',
                'ahmad_yani',
                'banjarbaru',
                'martapura',
                'pelaihari',
                'marabahan',
                'gambut',
                'kuala_pambuang',
                'nanga_bulik',
                'pangakalan_bun',
                'sampit',
                'sukamara'
            ],
            4 => [ // Kalimantan Timur
                'balikpapan_selatan',
                'samarinda_kota',
                'samarinda_seberang',
                'tenggarong',
                'kota_bangun',
                'melak',
                'samarinda_ulu',
                'samarinda_ilir',
            ],
            5 => [ // Kalimantan Utara
                'tanjung_selor',
                'tarakan',
            ],
            7 => [ // Sulawesi Tenggara
                'BAUBAU_KOTA-UP3_BAUBAU',
                'RAHA-UP3_BAUBAU',
                'MAWASANGKA',
                'WANGI_WANGI-UP3_BAUBAU-WANGI',
                'PASARWAJO',
                'WUA_WUA-UP3_KENDARI',
                'BENU_BENUA-UP3_KENDARI',
                'BOMBANA-UP3_KENDARI',
                'KOLAKA_UTARA-UP3_KENDARI',
                'UNAAHA-UP3_KENDARI',
                'KONAWE_SELATAN-UP3_KENDARI',
                'KOLAKA-UP3_KENDARI',
            ],
            10 => [ // Sulawesi Tengah
                'PALU_KOTA-UP3_PALU',
                'KAMONJI-UP3_PALU',
                'TAWAELI-UP3_PALU',
                'DONGGALA-UP3_PALU',
                'TAMBU-UP3_PALU',
                'PARIGI-UP3_PALU',
                'POSO-UP3_PALU',
                'KOLONEDALE-UP3_PALU',
                'BUNGKU-UP3_PALU',
                'TENTENA-UP3_TENTENA',
            ],
            11 => [ // Gorontalo
                'GORONTALO-UP3_GORONTALO',
                'KWANDANG-UP3_GORONTALO',
                'LIMBOTO-UP3_GORONTALO',
                'MARISA-UP3_GORONTALO',
                'TELAGA-UP3_GORONTALO',
            ],
            12 => [ // Nusa Tenggara Barat (NTB)
                'CAKRANEGARA',
                'TANJUNG',
                'AMPENAN',
                'GERUNG',
                'KOPANG',
                'PRAYA',
                'PRINGGABAYA',
                'SELONG',
                'SAPE',
                'DOMPU',
                'WOHA',
                'BIMA_KOTA',
                'ALAS',
                'TALIWANG',
                'EMPANG',
                'SAMAWA_REA',
            ],
            14 => [ // Maluku
                'SAUMLAKI',
                'MOA',
                'MASOHI',
                'BULA',
                'KAIRATU',
                'KOBISONTA',
                'PIRU',
                'TUAL',
                'ELAT',
                'DOBO',
                'MAKO',
                'BAGUALA',
                'SAPARUA',
                'AMBON_KOTA',
                'HARUKU',
                'NAMROLE',
                'BANDA',
                'NUSANIWE',
                'NAMLEA',
                'HITU',
            ],
            15 => [ // Maluku Utara
                'JAILOLO',
                'MABA',
                'SOFIFI',
                'WEDA',
                'TOBELO',
                'DARUBA',
                'TERNATE',
                'BACAN',
                'BOBONG',
                'DOFA',
                'LAIWUI',
                'SAKETA',
                'SANANA',
                'SOASIU',
            ],
            16 => [ // Papua
                'MERAUKE',
                'MERAUKE_KOTA',
                'TANAH_MERAH',
                'KEPI',
                'KURIK',
                'KUPRIK',
                'TIMIKA_KOTA',
                'TIMIKA_JAYA',
                'BIAK',
                'BIAK_KOTA',
                'SERUI',
                'WAROPEN',
                'YOMDORI',
                'SENTANI',
                'ABEPURA',
                'ARSO',
                'GENYEM',
                'JAYAPURA',
                'SARMI',
                'NABIRE',
                'NABIRE_KOTA',
                'WAMENA_KOTA',
            ],
            17 => [ // Papua Barat
                'MANOKWARI_KOTA',
                'BINTUNI',
                'PRAFI',
                'WASIOR',
                'AIMAS',
                'FAK-FAK',
                'KAIMANA',
                'SORONG',
                'SORONG_KOTA',
                'TEMINABUAN',
                'WAISAI',
            ],
        ];

        foreach ($ulpData as $provinsiId => $ulpList) {
            foreach ($ulpList as $ulp) {
                DB::table('ulp')->insert([
                    'nama_ulp'   => strtoupper('ULP_' . str_replace(' ', '_', $ulp)),
                    'id_provinsi' => $provinsiId,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]);
            }
        }
    }
}
