<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UlpSeeder extends Seeder
{
    public function run(): void
    {
        $ulpData = [
            1 => [ // Kalimantan Barat
                'singkawang',
                'sambas',
                'bengkayang',
                'sei duri',
                'sekura',
                'pemangkat',
                'sanggau',
                'sintang',
                'putussibau',
                'balai karangan',
                'sekadu',
                'nanga pinoh',
            ],
            2 => [ // Kalimantan Selatan
                'lambung mangkurat',
                'banjarbaru',
                'ahmad yani',
                'martapura',
                'pelaihari',
                'marabahan',
                'gambut',
            ],
            4 => [ // Kalimantan Timur
                'balikpapan selatan',
                'samarinda kota',
                'samarinda seberang',
                'tenggarong',
                'kota bangun',
                'melak',
                'samarinda ulu',
                'samarinda ilir',
            ],
            5 => [ // Kalimantan Utara
                'tanjung selor',
                'tarakan',
            ],
            7 => [ // Sulawesi Tenggara
                'BAUBAU KOTA',
                'RAHA',
                'MAWASANGKA',
                'WANGI-WANGI',
                'PASARWAJO',
                'WUA WUA',
                'BENU BENUA',
                'BOMBANA',
                'KOLAKA UTARA',
                'UNAAHA',
                'KONAWE SELATAN',
                'KOLAKA',
            ],
            10 => [ // Sulawesi Tengah
                'PALU KOTA – UP3 PALU',
                'KAMONJI – UP3 PALU',
                'TAWAELI – UP3 PALU',
                'DONGGALA – UP3 PALU',
                'TAMBU – UP3 PALU',
                'PARIGI – UP3 PALU',
                'POSO – UP3 PALU',
                'KOLONEDALE – UP3 PALU',
                'BUNGKU – UP3 PALU',
                'TENTENA – UP3 TENTENA',
            ],
            11 => [ // Gorontalo
                'GORONTALO – UP3 GORONTALO',
                'KWANDANG – UP3 GORONTALO',
                'LIMBOTO – UP3 GORONTALO',
                'MARISA – UP3 GORONTALO',
                'TELAGA – UP3 GORONTALO',
            ],
            12 => [ // Nusa Tenggara Barat (NTB)
                'CAKRANEGARA – KOTA MATARAM',
                'TANJUNG – KAB. LOMBOK UTARA',
                'AMPENAN – KOTA MATARAM',
                'GERUNG – KAB. LOMBOK BARAT',
                'KOPANG – KAB. LOMBOK TENGAH',
                'PRAYA – KAB. LOMBOK TENGAH',
                'PRINGGABAYA – KAB. LOMBOK TIMUR',
                'SELONG – KAB. LOMBOK TIMUR',
                'SAPE – KAB. BIMA',
                'DOMPU – KAB. DOMPU',
                'WOHA – KAB. BIMA',
                'BIMA KOTA – KOTA BIMA',
                'ALAS – KAB. SUMBAWA',
                'TALIWANG – KAB. SUMBAWA BARAT',
                'EMPANG – KAB. SUMBAWA',
                'SAMAWA REA – KAB. SUMBAWA',
            ],
            14 => [ // Maluku
                'SAUMLAKI – KAB. KEPULAUAN TANIMBAR',
                'MOA – KAB. MALUKU BARAT DAYA',
                'MASOHI – KAB. MALUKU TENGAH',
                'BULA (TERMASUK KP ONDOR, KP GESER, KP KIANDAARAT) – KAB. SERAM BAGIAN TIMUR',
                'KAIRATU (TERMASUK KP RUMAHKAY, KP LIANG) – KAB. SERAM BAGIAN BARAT',
                'KOBISONTA – KAB. MALUKU TENGAH (WILAYAH UTARA)',
                'PIRU – KAB. SERAM BAGIAN BARAT',
                'TUAL (TERMASUK UP KUR) – KOTA TUAL / MALUKU TENGGARA',
                'ELAT – KAB. MALUKU TENGGARA',
                'DOBO – KAB. KEPULAUAN ARU',
                'MAKO – KAB. KEPULAUAN ARU',
                'BAGUALA – KOTA AMBON (BAGUALA)',
                'SAPARUA – KAB. MALUKU TENGAH',
                'AMBON KOTA – KOTA AMBON',
                'HARUKU – KAB. MALUKU TENGAH',
                'NAMROLE – KAB. BURU SELATAN',
                'BANDA – KAB. MALUKU TENGAH (KEPULAUAN BANDA)',
                'NUSANIWE – KOTA AMBON',
                'NAMLEA – KAB. BURU',
                'HITU – KAB. MALUKU TENGAH',
            ],
            15 => [ // Maluku Utara
                'JAILOLO (TERMASUK KP SIDANGOLI) – KAB. HALMAHERA BARAT',
                'MABA – KAB. HALMAHERA TIMUR',
                'SOFIFI – KOTA SOFIFI / KAB. HALMAHERA BARAT–TENGAH',
                'WEDA – KAB. HALMAHERA TENGAH',
                'TOBELO (TERMASUK KP MALIFUT) – KAB. HALMAHERA UTARA',
                'DARUBA – KAB. PULAU MOROTAI',
                'TERNATE – KOTA TERNATE',
                'BACAN (TERMASUK KP JIKO) – KAB. HALMAHERA SELATAN',
                'BOBONG – KAB. PULAU TALIABU',
                'DOFA (TERMASUK KP MANGOLI) – KAB. KEPULAUAN SULA',
                'LAIWUI (TERMASUK KP MADOPOLO) – KAB. HALMAHERA SELATAN',
                'SAKETA – KAB. HALMAHERA SELATAN',
                'SANANA – KAB. KEPULAUAN SULA',
                'SOASIU',
            ],
            16 => [ // Papua
                'MERAUKE KOTA',
                'TANAH MERAH',
                'KEPI',
                'KURIK',
                'KUPRIK',
                'TIMIKA KOTA',
                'TIMIKA JAYA',
                'BIAK / BIAK KOTA',
                'SERUI',
                'WAROPEN',
                'YOMDORI',
                'SENTANI',
                'ABEPURA',
                'ARSO',
                'GENYEM',
                'JAYAPURA',
                'SARMI',
                'NABIRE / NABIRE KOTA',
                'WAMENA KOTA',
            ],
            17 => [ // Papua Barat
                'MANOKWARI KOTA',
                'BINTUNI',
                'PRAFI',
                'WASIOR',
                'AIMAS',
                'FAK-FAK / FAKFAK',
                'KAIMANA',
                'SORONG',
                'SORONG KOTA',
                'TEMINABUAN',
                'WAISAI',
            ],
        ];

        foreach ($ulpData as $provinsiId => $ulpList) {
            foreach ($ulpList as $ulp) {
                DB::table('ulp')->insert([
                    'nama_ulp'   => strtoupper('ULP_' . str_replace(' ', '_', $ulp)),
                    'id_provinsi' => $provinsiId,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]);
            }
        }
    }
}
